import {chromium} from '@playwright/test';
import {mkdirSync} from 'node:fs';
mkdirSync('.sited/qa',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.TEST_URL||'http://localhost:5175');
await page.getByRole('button',{name:'Jogar treino local'}).click();
await page.locator('canvas').waitFor();
await page.waitForTimeout(1500);
await page.screenshot({path:'.sited/qa/arena-setup.png'});
await page.getByRole('button',{name:'Manter estas cartas'}).click();await page.getByRole('button',{name:'Começar neste selo'}).click();
await page.waitForTimeout(2500);
await page.screenshot({path:'.sited/qa/arena-desktop.png'});
console.log({errors,hand:await page.locator('.fan-card').count()});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(800);await page.screenshot({path:'.sited/qa/arena-mobile.png'});
await browser.close();if(errors.length)process.exitCode=1;
